# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 20:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyrics', '0012_auto_20161207_1623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 20, 23, 32, 450955, tzinfo=utc))),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Lyric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set([('user', 'lyric')]),
        ),
    ]
