# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0013_auto_20161207_1718'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetaliQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 21, 18, 3, 888212, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='detaliquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='detaliquiz',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Vocabulary'),
        ),
        migrations.AlterUniqueTogether(
            name='detaliquiz',
            unique_together=set([('quiz', 'vocabulary')]),
        ),
    ]
