# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20161207_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetaliQuiz',
            new_name='DetailQuiz',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 8, 17, 20, 58, 441274, tzinfo=utc)),
        ),
    ]
