# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('context', models.TextField()),
                ('lannguage', models.CharField(choices=[('es', 'espaniol'), ('en', 'ingles')], default='en', max_length=2)),
                ('url_video', models.URLField(null=True)),
                ('published', models.DateTimeField()),
            ],
        ),
    ]
