# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_auto_20161206_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Author')),
                ('url_avatar', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lyric',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 15, 0, 9, 965384, tzinfo=utc)),
        ),
    ]
