# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0005_auto_20161207_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100, verbose_name='Detail')),
                ('url_pronunciation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 16, 28, 59, 966736, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 16, 28, 59, 965457, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='lyric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Lyric'),
        ),
    ]
