# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0007_auto_20161207_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsHasLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='lyric_id',
            new_name='lyric',
        ),
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 17, 41, 57, 978246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 17, 41, 57, 976369, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='authorshaslyrics',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Author'),
        ),
        migrations.AddField(
            model_name='authorshaslyrics',
            name='lyric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Lyric'),
        ),
        migrations.AlterUniqueTogether(
            name='authorshaslyrics',
            unique_together=set([('author', 'lyric')]),
        ),
    ]
