# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0009_auto_20161207_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionHasLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 17, 56, 0, 722224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 17, 56, 0, 720933, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='productionhaslyrics',
            name='lyric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Lyric'),
        ),
        migrations.AddField(
            model_name='productionhaslyrics',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.MusicProduction'),
        ),
        migrations.AlterUniqueTogether(
            name='productionhaslyrics',
            unique_together=set([('production', 'lyric')]),
        ),
    ]
