# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 18:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lyrics', '0010_auto_20161207_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 18, 0, 43, 323116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 18, 0, 43, 321756, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='yourlyrics',
            name='lyric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Lyric'),
        ),
        migrations.AddField(
            model_name='yourlyrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='yourlyrics',
            unique_together=set([('user', 'lyric')]),
        ),
    ]
