# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0012_auto_20161207_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 21, 18, 3, 879982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 7, 21, 18, 3, 878762, tzinfo=utc)),
        ),
    ]
